kind: pipeline
name: default

steps:
- name: tag
  image: debian:10
  commands:
  - apt-get update
  - apt-get install -y jq curl
  - curl -s 'https://api.github.com/repos/vector-im/riot-web/releases/latest' | jq -j -r '.name' > version
  - echo -n 'latest,' | cat - version > .tags
  - echo -n ',' | cat - version >> .tags
  - echo -n -$DRONE_BUILD_NUMBER >> .tags

- name: docker-riot-web
  image: plugins/docker
  settings:
    repo: tlemarchand/riot-web
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: quay-riot-web
  image: plugins/docker
  settings:
    repo: quay.io/tlemarchand/riot-web
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    registry: quay.io