kind: pipeline
name: default

steps:
- name: tag
  image: debian:10
  commands:
  - apt-get update
  - apt-get install -y jq curl
  - curl -s 'https://api.github.com/repos/vector-im/riot-web/releases/latest' | jq -r '.name' > version
  - echo -n 'latest,' | cat - version > .tags

- name: docker  
  image: plugins/docker
  settings:
    repo: tlemarchand/riot-web
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - version=$(<version)
